# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3fa0b1ec783b1259178aa4c42ce29a9a986a79be417cf5b67a99e44a746f7f690dda3b5a38535768fe146f46721d95a3be9c7cd7e2b8408fd24352609b75e88

test:
  secret_key_base: 19c20837c14d1b1c4af88aa6bd9116a3f91d4e6755d4274a185ebf3d3b741d74c11314f87f13f50ffa33b563144ad312248f1d8d0e2fa38e231065b43ce8cbfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
